CREATE SCHEMA 'lyrics';

CREATE TABLE cleanlyrics (
SongID INT NOT NULL AUTO_INCREMENT,
Song VARCHAR(100) NOT NULL, 
Artist VARCHAR(100) NOT NULL, 
Clean BOOLEAN NOT NULL, 
CONSTRAINT PK_cleanlyrics PRIMARY KEY (SongID)
);